<div class="page-header">
    <h1>Ajouter une vulnérabilité</h1>
</div>
<form action="/vulnerabilite/add" class="mb-2" method="POST">
  <div class="form-group">
    <label for="description">Description</label>
    <input name="description" type="text" value="<?php if(isset($vulnerabilite)){ echo $vulnerabilite->description; }?>" class="form-control" id="description" aria-describedby="description">
  </div>
  <div class="form-group">
    <label for="severite">Sévérité</label>
    <select name="severite" class="form-control" id="severite">
      <option value="1">basse</option>
      <option value="2">moyenne</option>
      <option value="3">haute</option>
    </select>
  </div>
  <div class="form-group">
    <label for="applications">Applications</label>
    <select multiple name="applications[]" class="form-control" id="applications">
        <?php foreach ($applications as $application) { ?>
            <option value="<?php echo $application->idApp; ?>"><?php echo $application->nomApp ?></option>
        <?php } ?>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Enregistrer</button>
</form>