<div class="page-header">
    <h1>Modifier une vulnérabilité</h1>
</div>
<form action="/vulnerabilite/update/<?php echo $vulnerabilite->idVuln ?>" class="mb-2" method="POST">
  <div class="form-group">
    <label for="description">Description</label>
    <input name="description" type="text" value="<?php echo $vulnerabilite->description; ?>" class="form-control" id="description" aria-describedby="description">
  </div>
  <div class="form-group">
    <label for="severite">Sévérité</label>
    <select name="severite" class="form-control" id="severite">
      <?php foreach($severites as $index => $severite){ ?>
        <option value="<?php echo $index + 1; ?>" <?php if($vulnerabilite->severite == $index + 1){ echo 'selected'; } ?>><?php echo $severite; ?></option>
      <?php } ?>
    </select>
  </div>
  <div class="form-group">
    <label for="applications">Applications</label>
    <select multiple name="applications[]" class="form-control" id="applications">
        <?php foreach ($applications as $application) { ?>
            <option value="<?php echo $application->idApp; ?>"><?php echo $application->nomApp ?></option>
        <?php } ?>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Mettre à jour</button>
</form>