<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Remediation</title>
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
        <div class="container">
            <nav class="nav">
                <a class="nav-link" href="/">Accueil</a>
                <a class="nav-link" href="/vulnerabilite">Vulnérabilités</a>
                <?php if($this->session->get('auth')){ ?>
                    <a class="nav-link" href="/session/end">Déconnexion</a>
                <?php } else { ?>
                    <a class="nav-link" href="/session">Connexion</a>
                <?php } ?>
            </nav>
        </div>
        <div class="container">
            <?php echo $this->flash->output() ?>
            <?php echo $this->getContent(); ?>
            <?php if($this->session->get('auth')){ ?>
                <p>Connecté en tant que <b><?php 
                    $auth = $this->session->get('auth');
                    echo $auth['nom'];
                ?></b> (<?php echo $auth['role']->libelle; ?>)</p>
            <?php } ?>
        </div>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="/js/modal.js"></script>
    </body>
</html>